lat: 40.135
lon: 104.997

#sources:
#  adsb:
#    host: 'labs.organicelement.com'
#    port: 30005
#  mlat:
#    host: 'labs.organicelement.com'
#    port: 30105

sources:
  adsb:
    host: 'localhost'
    port: 30005
  mlat:
    host: 'localhost'
    port: 30105
